name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./api/ -t zaied112454/qr-code-backend:latest
          docker build ./front-end-nextjs/ -t zaied112454/qr-code-frontend:latest
      - name: push image to docker hub
        run: |
          docker login -u zaied112454 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push zaied112454/qr-code-backend:latest
          docker push zaied112454/qr-code-frontend:latest
      - name: download images from dockerhub
        run: |
          docker pull zaied112454/qr-code-backend:latest
          docker pull zaied112454/qr-code-frontend:latest
      - name: run images
        run: |
          docker run -d -p 3000:3000 zaied112454/qr-code-frontend:latest
          docker run -d -p 5000:5000 zaied112454/qr-code-backend:latest
          
